baseurl = "lesnonalignes.fr"
languageCode = "fr"
title = "Les Non Alignés"
theme = "skeleton-jlafos"
relativeURLs = true
canonifyURLs = true

[params]
  piedpage = "Cie Les Non Alignés – nov 2016"
  logo = "/img/logo-na-fafafa.png"
